version: "3"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=Kz1NnwUZZpuqEGDf64WpdaN7824ngiV1PTpYcVF2Ugwtg8EZcpqt
      - MARIADB_DATABASE=kawa_db
      - MARIADB_USER=kawa
      - MARIADB_PASSWORD=Kz1NnwUZZpuqEGDf64WpdaN7824ngiV1PTpYcVF2Ugwtg8EZcpqt
    command: ['--init-file', '/etc/mysql/init.sql']
    volumes:
      - kawa_db:/var/lib/mysql
      - ./init.sql:/etc/mysql/init.sql:ro
    ports:
      - "3306:3306"

volumes:
  kawa_db:
