version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: kawa_db
    command: ['--init-file', '/etc/mysql/init.sql']
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/etc/mysql/init.sql:ro
    ports:
      - "3306:3306"

volumes:
  db_data: