version: "3"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    command: ['--init-file', '/etc/mysql/init.sql']
    volumes:
      - kawa_db:/var/lib/mysql
      - ./init.sql:/etc/mysql/init.sql:ro
    ports:
      - "3306:3306"

volumes:
  kawa_db:
